/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import FormAdministrator.FormDetaljiAdministratora;
import FormAdministrator.FormNoviAdministrator;
import FormAdministrator.FormPretragaAdministratora;
import FormMec.FormDetaljiMeca;
import FormTim.FormNoviTim;
import FormTim.FormPretragaTima;
import controller.ClientController;
import domain.Administrator;
import domain.Grad;
import domain.Igrac;
import domain.Mec;
import domain.StatistikaIgraca;
import domain.Tim;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import models.TableModelMecevi;
import models.TableModelStatistika;
import session.Session;

/**
 *
 * @author PC
 */
public class MainForm extends javax.swing.JFrame {

    Administrator a;
    Tim crveniTim;
    Tim plaviTim;
    ArrayList<Igrac> crveniIgraci;
    ArrayList<Igrac> plaviIgraci;

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setLocationRelativeTo(null);
        this.a = Session.getInstance().getTrenutnoUlogovani();
        lblUlogovani.setText("Ulogovani: "
                + a.getIme() + " " + a.getPrezime());
        popuniGradove();
        popuniTimove();
        tblStatistika.setModel(new TableModelStatistika());
        tblMecevi.setModel(new TableModelMecevi());
//        panelUnosStatistike.setEnabled(false);
//        cmbGrad.setEnabled(false);
//        txtRundePlavi.setEnabled(false);
//        txtRundeCrveni.setEnabled(false);
//        cmbMVP.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUlogovani = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panelUnosStatistike = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStatistika = new javax.swing.JTable();
        btnDodajStat = new javax.swing.JButton();
        btnObrisiStat = new javax.swing.JButton();
        btnDodajMec = new javax.swing.JButton();
        cmbIgrac = new javax.swing.JComboBox();
        txtBrojUbistva = new javax.swing.JFormattedTextField();
        txtBrojSmrti = new javax.swing.JFormattedTextField();
        cbMVP = new javax.swing.JCheckBox();
        cmbGrad = new javax.swing.JComboBox();
        cmbCrveniTim = new javax.swing.JComboBox();
        cmbPlaviTim = new javax.swing.JComboBox();
        txtRundeCrveni = new javax.swing.JFormattedTextField();
        txtRundePlavi = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMecevi = new javax.swing.JTable();
        btnDetalji = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        menuNoviAdmin = new javax.swing.JMenuItem();
        menuPretragaAdmina = new javax.swing.JMenuItem();
        menuMojiDetalji = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        menuNoviTim = new javax.swing.JMenuItem();
        menuPretragaTimova = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUlogovani.setText("Ulogovani");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Unos meca"));

        jLabel1.setText("Grad:");

        jLabel2.setText("Crveni tim:");

        jLabel3.setText("Plavi tim:");

        jLabel4.setText("Dobijene runde (crveni):");

        jLabel5.setText("Dobijene runde (plavi):");

        panelUnosStatistike.setBorder(javax.swing.BorderFactory.createTitledBorder("Unos statistike meca"));

        jLabel7.setText("Igrac:");

        jLabel8.setText("Broj ubistva:");

        jLabel9.setText("Broj smrti:");

        jLabel10.setText("MVP:");

        tblStatistika.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStatistika);

        btnDodajStat.setText("Dodaj statistiku");
        btnDodajStat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajStatActionPerformed(evt);
            }
        });

        btnObrisiStat.setText("Obrisi statistiku");
        btnObrisiStat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiStatActionPerformed(evt);
            }
        });

        btnDodajMec.setText("Dodaj mec");
        btnDodajMec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajMecActionPerformed(evt);
            }
        });

        cmbIgrac.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtBrojUbistva.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        txtBrojSmrti.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        javax.swing.GroupLayout panelUnosStatistikeLayout = new javax.swing.GroupLayout(panelUnosStatistike);
        panelUnosStatistike.setLayout(panelUnosStatistikeLayout);
        panelUnosStatistikeLayout.setHorizontalGroup(
            panelUnosStatistikeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(panelUnosStatistikeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUnosStatistikeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUnosStatistikeLayout.createSequentialGroup()
                        .addComponent(btnObrisiStat, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                        .addComponent(btnDodajStat, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelUnosStatistikeLayout.createSequentialGroup()
                        .addGroup(panelUnosStatistikeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(23, 23, 23)
                        .addGroup(panelUnosStatistikeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBrojSmrti)
                            .addGroup(panelUnosStatistikeLayout.createSequentialGroup()
                                .addComponent(cbMVP)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(panelUnosStatistikeLayout.createSequentialGroup()
                        .addGroup(panelUnosStatistikeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelUnosStatistikeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbIgrac, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtBrojUbistva))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUnosStatistikeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnDodajMec, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelUnosStatistikeLayout.setVerticalGroup(
            panelUnosStatistikeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUnosStatistikeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUnosStatistikeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbIgrac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUnosStatistikeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtBrojUbistva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUnosStatistikeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtBrojSmrti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUnosStatistikeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cbMVP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(panelUnosStatistikeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodajStat)
                    .addComponent(btnObrisiStat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDodajMec)
                .addContainerGap())
        );

        cmbGrad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbCrveniTim.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCrveniTim.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCrveniTimItemStateChanged(evt);
            }
        });

        cmbPlaviTim.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPlaviTim.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPlaviTimItemStateChanged(evt);
            }
        });

        txtRundeCrveni.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtRundeCrveni.setText("16");

        txtRundePlavi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtRundePlavi.setText("14");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(120, 120, 120)
                        .addComponent(cmbGrad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(92, 92, 92)
                        .addComponent(cmbCrveniTim, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(101, 101, 101)
                        .addComponent(cmbPlaviTim, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtRundeCrveni))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(25, 25, 25)
                        .addComponent(txtRundePlavi)))
                .addContainerGap())
            .addComponent(panelUnosStatistike, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbCrveniTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbPlaviTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtRundeCrveni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtRundePlavi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelUnosStatistike, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Odigrani mecevi"));

        tblMecevi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblMecevi);

        btnDetalji.setText("Detalji izabranog meca");
        btnDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetaljiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(btnDetalji, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDetalji)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jMenu6.setText("Administratori");

        menuNoviAdmin.setText("Novi administrator");
        menuNoviAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNoviAdminActionPerformed(evt);
            }
        });
        jMenu6.add(menuNoviAdmin);

        menuPretragaAdmina.setText("Pretraga administratora");
        menuPretragaAdmina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPretragaAdminaActionPerformed(evt);
            }
        });
        jMenu6.add(menuPretragaAdmina);

        menuMojiDetalji.setText("Moji detalji");
        menuMojiDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMojiDetaljiActionPerformed(evt);
            }
        });
        jMenu6.add(menuMojiDetalji);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Tim");

        menuNoviTim.setText("Novi tim");
        menuNoviTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNoviTimActionPerformed(evt);
            }
        });
        jMenu7.add(menuNoviTim);

        menuPretragaTimova.setText("Pretraga tima");
        menuPretragaTimova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPretragaTimovaActionPerformed(evt);
            }
        });
        jMenu7.add(menuPretragaTimova);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUlogovani)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUlogovani)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuNoviAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNoviAdminActionPerformed
        if (a.getAdministratorID() == 1) {
            new FormNoviAdministrator(this, true).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Nemate pristup ovoj operaciji!");
        }
    }//GEN-LAST:event_menuNoviAdminActionPerformed

    private void menuPretragaAdminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPretragaAdminaActionPerformed
        if (a.getAdministratorID() == 1) {
            new FormPretragaAdministratora(this, true).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Nemate pristup ovoj operaciji!");
        }
    }//GEN-LAST:event_menuPretragaAdminaActionPerformed

    private void menuMojiDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMojiDetaljiActionPerformed
        new FormDetaljiAdministratora(this, rootPaneCheckingEnabled, a).setVisible(true);
    }//GEN-LAST:event_menuMojiDetaljiActionPerformed

    private void menuNoviTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNoviTimActionPerformed
        new FormNoviTim(this, true).setVisible(true);
    }//GEN-LAST:event_menuNoviTimActionPerformed

    private void menuPretragaTimovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPretragaTimovaActionPerformed
        new FormPretragaTima(this, true).setVisible(true);
    }//GEN-LAST:event_menuPretragaTimovaActionPerformed

    private void cmbCrveniTimItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCrveniTimItemStateChanged

        if (cmbCrveniTim.getSelectedItem() == null || cmbPlaviTim.getSelectedItem() == null) {
            return;
        }

        try {

            crveniTim = (Tim) cmbCrveniTim.getSelectedItem();
            popuniIgrace();

        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_cmbCrveniTimItemStateChanged

    private void cmbPlaviTimItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPlaviTimItemStateChanged

        if (cmbCrveniTim.getSelectedItem() == null || cmbPlaviTim.getSelectedItem() == null) {
            return;
        }

        try {

            plaviTim = (Tim) cmbPlaviTim.getSelectedItem();
            popuniIgrace();

        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_cmbPlaviTimItemStateChanged

    private void btnDodajStatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajStatActionPerformed

        if (txtBrojUbistva.getText().isEmpty() || txtBrojSmrti.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Polja za broj ubistva i smrti moraju biti popunjena!");
            return;
        }

        Igrac i = (Igrac) cmbIgrac.getSelectedItem();
        int brojUbistva = Integer.parseInt(txtBrojUbistva.getText());
        int brojSmrti = Integer.parseInt(txtBrojSmrti.getText());
        boolean MVP = cbMVP.isSelected();

        TableModelStatistika tm = (TableModelStatistika) tblStatistika.getModel();

        if (tm.postojiIgrac(i)) {
            JOptionPane.showMessageDialog(this, "Vec ste uneli statistiku za tog igraca!");
            return;
        }

        if (MVP) {
            if (tm.postojiMVP()) {
                JOptionPane.showMessageDialog(this, "Vec je unet MVP!");
                return;
            }
        }

        StatistikaIgraca si = new StatistikaIgraca(null, brojSmrti, brojUbistva, brojSmrti,
                MVP, i.getTim(), i);

        tm.dodajStatistiku(si);

    }//GEN-LAST:event_btnDodajStatActionPerformed

    private void btnObrisiStatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiStatActionPerformed

        int row = tblStatistika.getSelectedRow();

        if (row >= 0) {
            TableModelStatistika tm = (TableModelStatistika) tblStatistika.getModel();
            tm.obrisiStatistiku(row);
        }

    }//GEN-LAST:event_btnObrisiStatActionPerformed

    private void btnDodajMecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajMecActionPerformed

        try {

            Grad grad = (Grad) cmbGrad.getSelectedItem();
            int rundeCrveni = Integer.parseInt(txtRundeCrveni.getText());
            int rundePlavi = Integer.parseInt(txtRundePlavi.getText());
            String MVP = "";

            TableModelStatistika tmStat = (TableModelStatistika) tblStatistika.getModel();

            if (tmStat.getLista().size() != 6) {
                JOptionPane.showMessageDialog(this, "Niste uneli statistiku za svakog igraca!");
                return;
            }
            
            if(!tmStat.postojiMVP()){
                JOptionPane.showMessageDialog(this, "Jedan igrac mora da bude MVP!");
                return;
            }

            for (StatistikaIgraca si : tmStat.getLista()) {
                if (si.isMVP()) {
                    MVP = si.getIgrac().getNickname();
                }
            }

            Mec m = new Mec(null, rundeCrveni, rundePlavi, MVP,
                    crveniTim, plaviTim, grad, a, tmStat.getLista());

            ClientController.getInstance().addMec(m);
            
            tmStat.clear();
            
            TableModelMecevi tmMec = (TableModelMecevi) tblMecevi.getModel();
            tmMec.refreshTable();
            
            JOptionPane.showMessageDialog(this, "Uspesno dodat mec.");

        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnDodajMecActionPerformed

    private void btnDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetaljiActionPerformed
        
        int row = tblMecevi.getSelectedRow();
        if (row >= 0) {
            Mec m = ((TableModelMecevi) tblMecevi.getModel()).getSelectedMec(row);
            new FormDetaljiMeca(this, rootPaneCheckingEnabled, m).setVisible(true);
        }
        
    }//GEN-LAST:event_btnDetaljiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalji;
    private javax.swing.JButton btnDodajMec;
    private javax.swing.JButton btnDodajStat;
    private javax.swing.JButton btnObrisiStat;
    private javax.swing.JCheckBox cbMVP;
    private javax.swing.JComboBox cmbCrveniTim;
    private javax.swing.JComboBox cmbGrad;
    private javax.swing.JComboBox cmbIgrac;
    private javax.swing.JComboBox cmbPlaviTim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblUlogovani;
    private javax.swing.JMenuItem menuMojiDetalji;
    private javax.swing.JMenuItem menuNoviAdmin;
    private javax.swing.JMenuItem menuNoviTim;
    private javax.swing.JMenuItem menuPretragaAdmina;
    private javax.swing.JMenuItem menuPretragaTimova;
    private javax.swing.JPanel panelUnosStatistike;
    private javax.swing.JTable tblMecevi;
    private javax.swing.JTable tblStatistika;
    private javax.swing.JFormattedTextField txtBrojSmrti;
    private javax.swing.JFormattedTextField txtBrojUbistva;
    private javax.swing.JFormattedTextField txtRundeCrveni;
    private javax.swing.JFormattedTextField txtRundePlavi;
    // End of variables declaration//GEN-END:variables

    public void exit() {
        this.dispose();
        System.exit(0);
    }

    private void popuniGradove() {
        try {
            ArrayList<Grad> gradovi = ClientController.getInstance().getAllGrad();

            cmbGrad.removeAllItems();

            for (Grad grad : gradovi) {
                cmbGrad.addItem(grad);
            }

        } catch (Exception ex) {
            Logger.getLogger(FormNoviTim.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void popuniTimove() {

        try {
            ArrayList<Tim> timovi = ClientController.getInstance().getAllTim();

            cmbCrveniTim.removeAllItems();
            cmbPlaviTim.removeAllItems();

            for (Tim tim : timovi) {
                cmbCrveniTim.addItem(tim);
                cmbPlaviTim.addItem(tim);
            }

        } catch (Exception ex) {
            Logger.getLogger(FormNoviTim.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void popuniIgrace() {

        try {

            crveniTim = (Tim) cmbCrveniTim.getSelectedItem();
            plaviTim = (Tim) cmbPlaviTim.getSelectedItem();

            crveniIgraci = ClientController.getInstance().getAllIgrac(crveniTim);
            plaviIgraci = ClientController.getInstance().getAllIgrac(plaviTim);

            cmbIgrac.removeAllItems();

            for (Igrac igrac : crveniIgraci) {
                cmbIgrac.addItem(igrac);
            }

            for (Igrac igrac : plaviIgraci) {
                cmbIgrac.addItem(igrac);
            }

        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
